<a href="https://colab.research.google.com/github/HarshKothari21/DataAnalysis_Practice/blob/master/Web%20Srapping/Stocks_Historical_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Web Srapping/Stocks_Historical_data.ipynb

In [3]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

# URL to scrape
data_url = "https://finance.yahoo.com/quote/AAPL/history/?frequency=1mo&period1=1104537600&period2=1735182270"

# Headers to mimic a browser visit
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
}

# Perform an HTTP GET request to fetch the webpage
response = requests.get(data_url, headers=headers)

# Check if the request was successful
if response.status_code == 200:
    # Parse the HTML content of the page
    soup = BeautifulSoup(response.content, "html.parser")

    # Find the table containing historical data
    table = soup.find("table", class_="table yf-j5d1ld")

    if table:
        # Extract table rows
        rows = table.find_all("tr")

        # Extract headers
        headers = [header.get_text(strip=True) for header in rows[0].find_all("th")]

        # Extract data rows
        data = []
        for row in rows[1:]:
            cols = row.find_all("td")
            if len(cols) > 0:  # Ensure row has data
                data.append([col.get_text(strip=True) for col in cols])

        # Create a DataFrame
        df = pd.DataFrame(data, columns=headers)

        # Display the DataFrame
        print(df)

        # Save to CSV
        df.to_csv("AAPL_historical_data.csv", index=False)
        print("Data saved to AAPL_historical_data.csv")
    else:
        print("Historical data table not found on the page.")
else:
    print(f"Failed to fetch the webpage. Status code: {response.status_code}")

             Date             Open    High     Low  \
0    Dec 24, 2024           255.37  258.21  255.31
1     Dec 1, 2024           237.27  258.21  237.16
2     Nov 8, 2024     0.25Dividend    None    None
3     Nov 1, 2024           220.97  237.81  219.71
4     Oct 1, 2024           229.52  237.49  221.33
..            ...              ...     ...     ...
289   Apr 1, 2005             1.50    1.59    1.21
290   Mar 1, 2005             1.61    1.61    1.39
291  Feb 28, 2005  2:1Stock Splits    None    None
292   Feb 1, 2005             1.38    1.62    1.37
293   Jan 1, 2005             1.16    1.39    1.12

    CloseClose price adjusted for splits.  \
0                                  258.20
1                                  258.20
2                                    None
3                                  237.33
4                                  225.91
..                                    ...
289                                  1.29
290                                  1.49
291                                  None
292                                  1.60
293                                  1.37

    Adj CloseAdjusted close price adjusted for splits and dividend and/or capital gain distributions.  \
0                                               258.20
1                                               258.20
2                                                 None
3                                               237.07
4                                               225.66
..                                                 ...
289                                               1.09
290                                               1.26
291                                               None
292                                               1.35
293                                               1.16

             Volume
0        20,965,006
1       833,285,500
2              None
3       891,640,600
4       930,736,000
..              ...
289  19,375,518,400
290  14,675,920,000
291            None
292  21,448,946,400
293  25,708,244,800

[294 rows x 7 columns]
Data saved to AAPL_historical_data.csv

In [5]:
df.Date = pd.to_datetime(df.Date)

In [18]:
df[(df.Date.dt.day == 1) & (df.Date.dt.month == 1)].reset_index(drop=True)

,Date,Open,High,Low,CloseClose price adjusted for splits.,Adj CloseAdjusted close price adjusted for splits and dividend and/or capital gain distributions.,Volume
0,2024-01-01,187.15,196.38,180.17,184.40,183.50,"1,187,219,300"
1,2023-01-01,130.28,147.23,124.17,144.29,142.79,"1,443,652,500"
2,2022-01-01,177.83,182.94,154.70,174.78,171.96,"2,108,446,000"
3,2021-01-01,133.52,145.09,126.38,131.96,129.04,"2,240,262,000"
4,2020-01-01,74.06,81.96,73.19,77.38,75.02,"2,934,370,400"
5,2019-01-01,38.72,42.25,35.50,41.61,39.74,"3,312,349,600"
6,2018-01-01,42.54,45.03,41.17,41.86,39.39,"2,638,717,600"
7,2017-01-01,28.95,30.61,28.69,30.34,28.10,"2,252,488,000"
8,2016-01-01,25.65,26.46,23.10,24.33,22.05,"5,087,392,000"
9,2015-01-01,27.85,30.00,26.16,29.29,26.09,"5,221,053,600"
10,2014-01-01,19.85,20.01,17.63,17.88,15.60,"8,765,954,400"
11,2013-01-01,19.78,19.82,15.54,16.27,13.84,"13,123,423,600"
12,2012-01-01,14.62,16.37,14.61,16.30,13.75,"6,859,854,400"
13,2011-01-01,11.63,12.45,11.60,12.12,10.22,"10,841,535,600"
14,2010-01-01,7.62,7.70,6.79,6.86,5.79,"15,168,994,400"
15,2009-01-01,3.07,3.47,2.79,3.22,2.72,"18,105,740,800"
16,2008-01-01,7.12,7.15,4.51,4.83,4.08,"35,173,888,400"
17,2007-01-01,3.08,3.49,2.92,3.06,2.58,"27,209,781,200"
18,2006-01-01,2.59,3.09,2.53,2.70,2.27,"21,878,371,200"
19,2005-01-01,1.16,1.39,1.12,1.37,1.16,"25,708,244,800"

In [23]:
df[(df.Date.dt.day == 29) & (df.Date.dt.month == 12)].reset_index(drop=True)

Empty DataFrame
Columns: [Date, Open, High, Low, CloseClose price adjusted for splits., Adj CloseAdjusted close price adjusted for splits and dividend and/or capital gain distributions., Volume]
Index: []